build:
  nodes:
    analysis-and-tests:
      environment:
        php:
          version: '8.4'
      dependencies:
        override:
          - composer update --with orchestra/testbench:^10.0 --with illuminate/console:^12.0 --with illuminate/support:^12.0 --prefer-dist --no-interaction --no-progress
      tests:
        override:
          - php-scrutinizer-run
          - vendor/bin/phpunit

filter:
  paths:
    - src/*
  excluded_paths:
    - src/Console/Commands/stubs/*

checks:
  php: true

coding_style:
  php:
    spaces:
      within:
        brackets: true
